### ISSUE TITLE
Consider renaming default branch from master to main

### ISSUE THREAD

**Issue by coke** [Raku/problem-solving#298] opened 2021-09-16 02:05 UTC
Please consider renaming the default branch for existing Raku-related repositories from master to main.

https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by lizmat** [comment] 2021-09-16 08:08
FWIW, I think the plan is to have the RakuAST branch become "main" at some point for rakudo/rakudo.

But generally the problem is really the number of outstanding PRs that would get invalidated by the default branch change, no?

**Comment by coke** [comment] 2021-09-16 15:11
I think GitHub automatically fixes those.

**Comment by lizmat** [comment] 2021-09-16 16:26
They do?  That would be excellent.  It was my impression that they didn't, so a reason not to just move forward on this.

**Comment by coke** [comment] 2021-09-16 18:54
https://github.com/github/renaming#renaming-existing-branches

**Comment by vrurg** [comment] 2022-12-11 01:51
Closing as resolved. #356

**Closed by vrurg** 2022-12-11 01:51 UTC
Labels: rakudo, fallback
